name: Build Aseprite

on:
  push:
    branches:
      - main  # или другая ветка, по которой вы хотите запускать сборку
  pull_request:
    branches:
      - main  # или другая ветка, по которой вы хотите запускать сборку

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest' # или укажите конкретную версию, если требуется

      - name: Install dependencies
        run: |
          choco install cmake --version=3.21.0
          choco install ninja

      - name: Create build directory and configure CMake
        run: |
          mkdir C:\aseprite
          cd C:\aseprite
          git clone https://github.com/aseprite/aseprite.git .
          mkdir build
          cd build
          cmake -G Ninja -DLAF_BACKEND=skia ..

      - name: Build Aseprite
        run: |
          cd C:\aseprite\build
          ninja aseprite

      - name: Package Aseprite
        run: |
          cd C:\aseprite\build
          Compress-Archive -Path "bin\aseprite.exe" -DestinationPath "aseprite-package.zip"

      - name: Upload Aseprite Package
        uses: actions/upload-artifact@v3
        with:
          name: aseprite-package
          path: C:\aseprite\build\aseprite-package.zip
