name: Build Aseprite

on:
  workflow_dispatch:
    inputs:
      update_release:
        description: 'Update to latest Aseprite release'
        required: false
        default: 'false'
        type: boolean
  schedule:
    - cron: '0 0 * * 0' # Weekly schedule (e.g., every Sunday)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Aseprite Repository
        uses: actions/checkout@v3
        with:
          repository: <your-username>/aseprite # Replace with your Aseprite fork or original repo
          ref: main # Replace with the branch or tag you want to build

      - name: Install Dependencies
        run: |
          choco install cmake --version=3.23.5
          choco install ninja
          choco install visualstudio2022buildtools

      - name: Set up Visual Studio environment
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -arch=x64

      - name: Set up Skia dependencies
        run: |
          mkdir C:\deps
          cd C:\deps
          git clone https://skia.googlesource.com/skia.git
          cd skia
          python tools/git-sync-deps

      - name: Build Aseprite
        run: |
          cd aseprite
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DLAF_BACKEND=skia -DSKIA_DIR=C:/deps/skia -DSKIA_LIBRARY_DIR=C:/deps/skia/out/Release-x64 -G Ninja ..
          ninja aseprite
        env:
          BUILD_TYPE: Release
          ASEPRITE_VERSION: v1.3.8.1

      - name: Check if build was successful
        run: |
          if not exist "build/bin/aseprite.exe" exit /b 1
          echo "Build successful"
