name: Build Aseprite on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install ninja
          choco install python # Убедитесь, что Python установлен для выполнения git-sync-deps

      - name: Set up Skia
        run: |
          echo "Cloning Skia..."
          git clone https://skia.googlesource.com/skia.git skia
          cd skia
          echo "Running git-sync-deps..."
          python tools/git-sync-deps
          echo "Listing contents of Skia directory..."
          dir

      - name: Verify Skia Contents
        run: |
          echo "Verifying Skia directory contents..."
          dir skia
          dir skia/out/Release-x64

      - name: Configure Aseprite build
        run: |
          mkdir build
          cd build
          echo "Running CMake configuration..."
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=../skia -DSKIA_LIBRARY_DIR=../skia/out/Release-x64 -DSKIA_LIBRARY=../skia/out/Release-x64/skia.lib -G Ninja ..

      - name: Build Aseprite
        run: |
          cd build
          echo "Running Ninja build..."
          ninja aseprite

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aseprite-build
          path: build/bin/aseprite.exe
